version: "3.9"

services:
  nexus-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-web
    env_file: .env # Novo: Mapeamento para o arquivo de variáveis de ambiente
    ports:
      - "8000:8000"
    volumes:
      - ./apps:/code/apps
      - ./shared-lib:/code/shared-lib
      - ./tools:/code/tools
    # environment:
    #   - ENV=production # Removido, agora está no .env
    restart: unless-stopped